name: flutter_module
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  pretty_dio_logger: ^1.4.0
  dio: ^5.8.0+1
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  flutter_highlight: ^0.7.0
  flutter_riverpod: ^2.6.1
  pull_to_refresh: ^2.0.0
  video_player: 2.7.2
  linked_scroll_controller: ^0.2.0
  scrollview_observer: ^1.26.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: 5.3.2
  build_runner: 2.3.3

flutter_gen:
  output: lib/resource/

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/capture/

  module:
    androidX: true
    androidPackage: com.jack.flutter_module
    iosBundleIdentifier: com.jack.flutterModule
